### ISSUE TITLE
Question: E-Mail-Adress with local part containing only slashes valid?

### ISSUE THREAD

**Issue by PascalSchumacher** [RohanNagar/jmail#136]
Is `------------------@ab.org` a valid e-mail address?

JMail says it is valid, but both `Postfix` and `Apache James` reject it. Resulting in:

```
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 5.1.3 Bad recipient address syntax
	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
```

when I use Java Mail to try to deliver it to these e-mail servers.

By the way: Thank you very much for providing JMail.

**Comment by RohanNagar** [comment]
Hey @PascalSchumacher, thanks for opening this issue. That is a strange looking address but it should be valid according to RFC. Running validators other than JMail also show this address as valid:

```java
@Test
void dashTest() {
  String addr = "------------------@ab.org";

  implementations.forEach(impl -> {
    String implRes = impl.runTest(addr, true);
    System.out.println(impl.name + ": " + implRes);
  });
}
```

Results in:

```
JMail: Valid in 103,967.23 ns
Apache Commons: Valid in 214,597.66 ns
Jakarta (Javax) Mail: Valid in 68,910.55 ns
email-rfc2822: Valid in 334,543.4 ns
```

It seems like these mail servers are being a little too strict in their validation 🙂

You could always add a rule to your validator to reject these kinds of addresses. Something like this should work:

```java
EmailValidator validator = JMail.strictValidator()
  // Ensure that the local-part is not made up of all - characters
  .withRule(email -> email.localPartWithoutComments().length() != email.localPart().chars().filter(c -> c == '-').count());
```

**Comment by PascalSchumacher** [comment]
Thank you very much :) and sorry for wasting your time!

**Comment by RohanNagar** [comment]
No worries, please feel free to continue opening issues like this. I like to check out the edge cases 🙂
