### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ea234** [RohanNagar/jmail#19]
+ eMail ABC.DEF@GHI.JKL      (MNO) is valid

E Error ABC.DEF@GHI.         (MNO)
index 0,length 0
java.lang.StringIndexOutOfBoundsException: index 0,length 0
	at java.base/java.lang.String.checkIndex(String.java:3278)
	at java.base/java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:307)
	at java.base/java.lang.StringBuilder.charAt(StringBuilder.java:85)
	at com.sanctionco.jmail.JMail.internalTryParse(JMail.java:374)
	at com.sanctionco.jmail.JMail.tryParse(JMail.java:100)
	at com.sanctionco.jmail.JMail.isValid(JMail.java:67)
	at de.fk.email.TestJMail1.isValid(TestJMail1.java:20)
	at de.fk.email.TestJMail1.main(TestJMail1.java:10)

E Error ABC.DEF@GHI.JKL       .  
index 0,length 0
java.lang.StringIndexOutOfBoundsException: index 0,length 0
	at java.base/java.lang.String.checkIndex(String.java:3278)
	at java.base/java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:307)
	at java.base/java.lang.StringBuilder.charAt(StringBuilder.java:85)
	at com.sanctionco.jmail.JMail.internalTryParse(JMail.java:374)
	at com.sanctionco.jmail.JMail.tryParse(JMail.java:100)
	at com.sanctionco.jmail.JMail.isValid(JMail.java:67)
	at de.fk.email.TestJMail1.isValid(TestJMail1.java:20)
	at de.fk.email.TestJMail1.main(TestJMail1.java:11)

public class TestJMail1
{
  public static void main( String[] args )
  {
    isValid( "ABC.DEF@GHI.JKL      (MNO)" );
    isValid( "ABC.DEF@GHI.         (MNO)" );
    isValid( "ABC.DEF@GHI.JKL       .  " );

    System.exit( 0 );
  }

  private static boolean isValid( String pInput )
  {
    try
    {
      if ( JMail.isValid( pInput ) )
      {
        System.out.println( "+ eMail " + pInput + " is valid" );

        return true;
      }

      System.out.println( "- eMail " + pInput + " is not valid" );
    }
    catch ( Exception err_inst )
    {
      System.out.println( "\n\nE Error " + pInput );

      System.out.println( err_inst.getMessage() );

      err_inst.printStackTrace( System.out );

      System.out.println( "\n" );
    }

    return false;
  }
}

**Comment by RohanNagar** [comment]
Thank you for the detailed report! I am currently on vacation but will try to take a look next week.
